# Add labels based on project
BICAN:
    - 'BICAN'
BICCN:
    - 'BICCN'
SCORCH:
    - 'SCORCH'
ManifestValidation:
    - 'Manifest Validation'
CVTerms:
    - 'Controlled vocabulary terms'
FileUpload:
    - 'File upload'
PublicFileAccess:
    - 'Accessing public files'
RestrictedFileAccess:
    - 'Accessing restricted files'
LandingPagesPublications:
    - 'Landing pages/ publications'
