name: CV request
description: Request a new controlled vocabulary term for use in a submission manifest
title: "[NeMO CV request]: "
labels: ["USER_ISSUE"]
assignees:
  - JPReceveur
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reaching out to the NeMO team about adding a new cv term. Please provide the information below.

  - type: dropdown
    id: Project
    attributes:
      label: Project
      description: What project are you associated with?
      options:
        - BICAN
        - BICCN
        - SCORCH
        - Other
    validations:
      required: true
  - type: input
    id: cvfield
    attributes:
      label: Please provide the manifest field which you would like to request a new term.
      placeholder: e.g. Technique
    validations:
      required: true
      
- type: input
    id: Proposed CV term
    attributes:
      label: Please provide the proposed term name
      description: New terms must be in all lowercase, without spaces, commas, semicolons, or special characters
      placeholder: term_name
    validations:
      required: true
        
  - type: textarea
    id: Definition of cv term
    attributes:
      label: Please provide a suggested definition for the suggested term
      description: 
      placeholder: Please provide a suggested definition here (max 100 words)
    validations:
      required: true

  - type: checkboxes
    id: terms
    attributes:
      label: The information in this ticket contains only public information
      description: DO NOT INCLUDE ANY CONTROLLED ACCESS OR PERSONAL IDENTIFYING INFORMATION, these issues are publicly viewable. If you need to share anything that is not public, please email nemo@som.umaryland.edu
      options:
        - label: There is no personally identifiable or restricted information included in this ticket
          required: true

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: In some cases we may contact you directly rather than responding to the github ticket (e.g., in the case of potentially sensitive information). Please provide an alternate contact
      placeholder: e.g. email@example.com
    validations:
      required: false
